### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by talantbekov123** [maximumsweet/sprint10#3]
Здравствуйте. Благодарю за проделанную работу! К сожалению текущая реализация содержит недостаток, не позволяющий мне засчитать работу на данной итерации:

**Надо исправить**
- В репозитории не указали версии. По умолчанию, команда git push не отправляет теги на удалённые сервера. После создания тегов нужно отправлять явно на удалённый сервер. Процесс аналогичен отправке веток — достаточно выполнить команду `git push origin <tagname>` или `git push origin --tags`. Подробнее можно ознакомиться [тут](https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8#r_git_tagging) 
 - Не проходят валидацию адреса с поддоменами. Например: http://some.test.yandex.ru
- Проверку проходит следующий некорректный адре сайта http://ya.ru:00000 (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Можно лучше:**
- файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.

**Comment by maximumsweet** [comment]
**Здравствуйте!**
Все замечания исправил, надеюсь теперь всё правильно. Прошу Вас перепроверить.

**Comment by talantbekov123** [comment]
Здравствуйте. Работа проделана хорошо! Прошу исправить проверку адреса сайта, после чего смогу пропустить работу.

**Надо исправить**
Проверку проходит следующий некорректный адрес сайта http://11.11.11.11:0000. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Отлично**
- эффективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Comment by maximumsweet** [comment]
Здравствуйте! Исправил, прошу проверить.

**Comment by talantbekov123** [comment]
Отличная работа!
**Особенно понравилось что включили в сет регулярки точки, подчеркивания в e-mail!**

- эффективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
